import { findPortMethodParam } from './validateProfile';

export function formatCommand(adapter, port, method, param) {
    if (adapter.model === 'iTachIP2CC') {
        return `${adapter.ip}: Relay ${param.position} ${param.name}`;
    }
    let command = method.command;
    if (method.type === 'actions' && param) {
        command = command.replace('%', param.value);
    }
    return `${adapter.ip}: ${command}`;
}

function findAdapterForPort(json, portId) {
    return json.adapters.find((a) => (a.ports || []).some((p) => p.id === portId));
}

function applyITachIP2CCMethods(json) {
    json.adapters
        .filter((adapter) => adapter.model === 'iTachIP2CC')
        .forEach((adapter) => {
            adapter.ports.forEach((port) => {
                port.methods = [
                    {
                        name: 'Power',
                        id: 'power',
                        params: [
                            { name: 'On', id: 'on', position: port.position },
                            { name: 'Off', id: 'off', position: port.position },
                        ],
                    },
                ];

                // The autogenerated method gets the same main_method treatment as
                // any other primary control, so we add the style and let it flow
                // through the normal style-inlining pass below.
                if (!Array.isArray(json.styles)) json.styles = [];
                json.styles.push(port.id + '.main_method=power');
            });
        });
}

function applyStyles(json) {
    if (!Array.isArray(json.styles) || json.styles.length === 0) return;

    const styleRegex =
        /^(?<port>[^.=]*)\.?(?<method>[^.=]*)\.?(?<param>[^.=]*)\.(?<style>[^.=]*)=(?<value>.*)$/;

    json.styles.forEach((style) => {
        if (style.includes('..')) return;
        const result = styleRegex.exec(style);
        if (!result) return;

        let port = null;
        for (const adapter of json.adapters) {
            const found = (adapter.ports || []).find((p) => p.id === result.groups.port);
            if (found) {
                port = found;
                break;
            }
        }
        if (!port) return;

        switch (result.groups.style) {
            case 'icon': {
                const icon = result.groups.value;
                if (result.groups.method) {
                    const method = port.methods.find((m) => m.id === result.groups.method);
                    if (!method) return;
                    if (result.groups.param) {
                        const param = (method.params || []).find(
                            (p) => p.id === result.groups.param
                        );
                        if (param) param.icon = icon;
                    } else {
                        method.icon = icon;
                    }
                } else {
                    port.icon = icon;
                }
                break;
            }
            case 'main_method': {
                port.main_method = port.methods.find(
                    (m) => m.id === result.groups.value
                );
                break;
            }
            case 'invisible': {
                if (!result.groups.param) {
                    const method = port.methods.find(
                        (m) => m.id === result.groups.method
                    );
                    if (method) method.visible = result.groups.value !== 'true';
                }
                break;
            }
        }
    });
}

function applyVisibility(json) {
    json.adapters.forEach((adapter) => {
        adapter.ports.forEach((port) => {
            port.showOnlyMainMethod = Boolean(port.main_method && port.methods.length === 1);

            port.methods.forEach((method) => {
                if (port.main_method && method.id === port.main_method.id) {
                    method.visible = false;
                }
                if (method.visible !== false) {
                    method.visible = true;
                }
            });
        });
    });
}

function resolveScenes(json) {
    if (!Array.isArray(json.scenes)) return;

    json.scenes.forEach((scene) => {
        scene.resolvedCommands = scene.commands.map((commandRef) => {
            const { port, method, param } = findPortMethodParam(json, commandRef);
            const adapter = findAdapterForPort(json, port.id);
            return formatCommand(adapter, port, method, param);
        });
    });
}

export function transformProfile(json) {
    applyITachIP2CCMethods(json);
    applyStyles(json);
    applyVisibility(json);
    resolveScenes(json);
    return json;
}
